/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package com.eomcs.lms;

import java.util.Scanner;
public class App {
  public static void main(String[] args) {
    Scanner keyboard = new Scanner(System.in); 

    System.out.print("번호? ");
    String no = keyboard.nextLine();
    System.out.print("수업명? ");
    String title = keyboard.nextLine();
    System.out.print("설명? ");
    String description = keyboard.nextLine();
    System.out.print("시작일? ");
    String startDate = keyboard.nextLine();
    System.out.print("종료일? ");
    String endDate = keyboard.nextLine();
    System.out.print("총수업시간? ");
    String totalHours = keyboard.nextLine();
    System.out.print("일수업시간? ");
    String dayHours = keyboard.nextLine();
    
    
    System.out.println();



    System.out.printf("번호: %s \n", no);
    System.out.printf("수업명: %s \n", title);
    System.out.printf("설명: %s \n", description);
    System.out.printf("기간: %s ~ %s \n", startDate, endDate); 
    System.out.printf("총수업시간: %s 시간 \n", totalHours);
    System.out.printf("일수업시간: %s 시간 \n", dayHours); 
    
    keyboard.close();
  }
}
