/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package com.bitcamp.myproject;

public class App {
  public static void main(String[] args) {
    // 카페 명단 출력
    
    System.out.println("카페 명단");
    System.out.println("카페 수 : 100개");
    System.out.println("상호 : 카페 0336");
    System.out.println("지역 : 경기도");
    System.out.println("메뉴 : 아메리카노");
    System.out.println("별점 : 5개");
    

    
  }

}
