/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package com.bitcamp.myproject;

public class App {
	public static void main(String[] args) {
		System.out.println("카페");
	}

}
